interface/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('plotter/', include(('plotter.urls', 'plotter'), namespace='plotter')),
    path('admin/', admin.site.urls),
]

plotter/urls.py
from django.urls import path

from plotter.views.bot_view import BotView

urlpatterns = [
    path('', BotView.as_view(), name='index'),
    path('update/', BotView.as_view(), name='update'),
]

plotter/models.py
from django.db import models

# Create your models here.

plotter/views/bot_view.py
import json
from datetime import datetime
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import TemplateView
from django.conf import settings

#from examples.bot_3 import BotMovingAverage
from examples.bot_2 import BotRsi
from context.crypto.data.backtest import BackTest
from context.crypto.infra.backtest_interface_impl import BackTestInterfaceImpl
from context.wallet.domain.entities.wallet import Wallet
from context.strategy.domain.entities.moving_average import MovingAverage
from context.strategy.domain.entities.rsi import Rsi

class BotView(TemplateView):
    TEMPLATE = "plotter/graph.html"

    repository = BackTestInterfaceImpl(
            BackTest(filename=settings.EXTERNAL_LIBS_PATH + "\\context\\crypto\\data\\btc.json"),
            datetime.strptime("2018-04-01", "%Y-%m-%d"),
            datetime.strptime("2021-01-24", "%Y-%m-%d"))

    wallet = Wallet("wallet", "Wallet Test", resources=1000.00)
    
    strategy = Rsi(period=14)

    bot = BotRsi(
        "id1",
        "Bot to RSI",
        repository,
        strategy,
        wallet)

    def get(self, request):
        if request.is_ajax():
            try:
                action, operation, currency, mm_value = self.bot.operate()

                wallet_resume = self.wallet.resume('BTC')

                data = {
                    'action': action,
                    'price': currency.last,
                    'timestamp': datetime.strftime(currency.timestamp, "%Y-%m-%d %H:%M:%S"),
                    'wallet': {
                        'qnt': wallet_resume.qnt,
                        'value': wallet_resume.mean_price,
                        'free': round(self.wallet.resources * 1.0, 2),
                        'now': round(wallet_resume.qnt * currency.last + self.wallet.resources, 2)
                    }
                }

                return HttpResponse(json.dumps(data))
            
            except Exception as e:
                print(e)
                return HttpResponse(None)
            
        else:
            context = {'currency': self.repository.get('BTC')}

            return render(request, self.TEMPLATE, context)

plotter/templates/plotter/card.wallet.html
<div class="card text-dark bg-warning mb-3" style="max-width: 18rem;">
    <div class="card-header">Wallet</div>
    <div class="card-body">
      <h5 class="card-title">BTC</h5>
      <p id="position_btc" class="card-text">0.00000000</p>
      <p id="position_free" class="card-text">U$ 00,00</p>
      <p id="position_total" class="card-text">U$ 00,00</p>
    </div>
</div>

plotter/templates/plotter/graph.html
{% load static %}
<html>
    <head>
        <title>Bot Plotter</title>
        <link href="{% static 'fontawesome/5.15.1/css/all.min.css' %}" rel="stylesheet">
        <link href="{% static 'bootstrap/5.0.0/css/bootstrap.min.css' %}" rel="stylesheet">
    </head>

    <body>
        <div class="container" style="width: 75%;">
            <br>
            <div class="container">
                <div class="row">
                    <div class="col-sm w-25 p-3 d-flex align-items-center">
                        {% include "plotter/card.wallet.html" %}
                    </div>
                    <div class="col-sm d-flex align-items-center">
                        <button id='pause' type="button" class="btn btn-primary"><i class="fas fa-2x fa-pause-circle"></i></button>
                    </div>
                </div>
            </div>
            <br>
            <canvas class="chartjs-render-monitor" id="myChart" width="905" height="452" style="display: block; height: 362px; width: 724px;"></canvas>
            <br>
            <hr>
            <br>
        </div>
    </body>

    <script src="{% static 'jquery/3.5.1/jquery.min.js' %}"></script>
    <script src="{% static 'moment/2.29.1/moment.min.js' %}"></script>
    <script src="{% static 'chart.js/2.9.4/Chart.min.js' %}"></script>
    <script src="{% static 'bootstrap/5.0.0/js/bootstrap.bundle.min.js' %}"></script>

    <script>
        var myChart = null;
        var paused = false;
        window.onload = function() {
            var ctx = document.getElementById('myChart').getContext('2d');
            myChart = new Chart(ctx, {
                type: 'line',
                data: {
                    datasets: [{
                        label: 'Price',
                        borderColor: "#3434FF",
                        pointRadius: 0,
                        fill: false,    
                        data: []
                    },
                    {
                        label: 'Buy',
                        backgroundColor: "#00FF00",
                        borderColor: "#00FF00",
                        showLine: false,
                        pointRadius: 5,
                        fill: false,    
                        data: []
                    },
                    {
                        label: 'Sell',
                        backgroundColor: "#FF0000",
                        borderColor: "#FF0000",
                        showLine: false,
                        pointRadius: 5,
                        fill: false,    
                        data: []
                    }]
                },
                options: {
                    responsive: true,
                    scales: {
                        xAxes: [{
                            type: 'time',
                            distribution: 'series',
                            offset: true,
                            time: {
                                displayFormats: {
                                    day: 'DD-MM-YYYY'
                                }
                            }
                        }],
                        yAxes: [{
                            display: true,
                            scaleLabel: {
                                display: true,
                            },
                            ticks: {
                                beginAtZero: false
                            }
                        }]
                    }
                }
            });
        }

        function poll() {
            if (!paused) {
                $.ajax({
                    url: "{% url 'plotter:update' %}",
                    type: "GET",
                    success: function(data) {
                        var time = new String(data['timestamp']);
                        var currency = data['price'];
                        var action = new String(data['action']);

                        // Add prices
                        var prices = myChart.data.datasets[0].data;
                        prices.push({
                            x: moment(time, 'YYYY-MM-DD HH:mm:ss'),
                            y: currency
                        });
                        
                        // Add buy or sell
                        if (action == "buy") {
                            var buys = myChart.data.datasets[1].data;
                            buys.push({
                                x: moment(time, 'YYYY-MM-DD HH:mm:ss'),
                                y: currency
                            });
                        } else if (action == "sell") {
                            var sells = myChart.data.datasets[2].data;
                            sells.push({
                                x: moment(time, 'YYYY-MM-DD HH:mm:ss'),
                                y: currency
                            });
                        }

                        // Update Wallet Card
                        $("#position_btc").empty();
                        $("#position_btc").append(data['wallet']['qnt'])
                        $("#position_free").empty();
                        $("#position_free").append("U$ " + data['wallet']['free'] + ",00")
                        $("#position_total").empty();
                        $("#position_total").append("U$ " + data['wallet']['now'])

                        // if (prices.length > 30) {
                        //     var base_slice_data = null;
                        //     myChart.data.datasets[0].data = prices.slice(1, 30);
                        //     base_slice_data = myChart.data.datasets[0].data[0].x;
                        //     var buys = myChart.data.datasets[1].data;
                        //     var slice_idx = -1;
                        //     for (var i = 0 ; i < buys.length ; i++) {
                        //         if (buys[i].x.isSame(base_slice_data)) {
                        //             slice_idx = i;
                        //             break;
                        //         }
                        //     }
                            
                        //     if (slice_idx >= 0) {
                        //         myChart.data.datasets[1].data = buys.slice(slice_idx, buys.length - 1);
                        //     }
                        //     var slice_idx = -1;
                        //     var sells = myChart.data.datasets[2].data;
                        //     for (var i = 0 ; i < sells.length ; i++) {
                        //         if (sells[i].x.isSame(base_slice_data)) {
                        //             slice_idx = i;
                        //             break;
                        //         }
                        //     }
                        //     if (slice_idx >= 0) {
                        //         myChart.data.datasets[2].data = sells.slice(slice_idx, sells.length - 1);
                        //     }
                        // }
                        
                        myChart.update();
                    },
                    dataType: "json",
                    complete: setTimeout(function() {poll()}, 20),
                    timeout: 5000
                });
            }
        }

        document.addEventListener("DOMContentLoaded", function () {
            (poll())();
        });

        $("#pause").click(function() {
            paused = !paused;
            if (paused) {
                $("#pause i").toggleClass('fa-play-circle fa-pause-circle');
            } else {
                $("#pause i").toggleClass('fa-pause-circle fa-play-circle');
                poll();
            }
        });
    </script>
</html>